[package]
name = "supra"
edition = "2024.beta"
published-at = "0xb2133239f65654e65eba7432ed0a5364a2e8a842282fe4aa19daf1132959628b"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
sui = "0x2"
supra = "0xb2133239f65654e65eba7432ed0a5364a2e8a842282fe4aa19daf1132959628b"

[dev-dependencies]

[dev-addresses]
