[package]
name = "faucet"
edition = "2024.beta"
# published-at = "0x76ab030e93509eaeac54d7feb270c95af5f5b38c56584cbfedc747efaac63636"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
faucet = "0x0"

[dev-addresses]
