services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  guardiand:
    image: ghcr.io/wormhole-foundation/guardiand:latest
    container_name: guardiand    
    entrypoint: /guardiand
    command: spy --nodeKey /node.key --spyRPC "[::]:7073" --network /wormhole/testnet/2/1 --bootstrap "/dns4/t-guardian-01.nodes.stable.io/udp/8999/quic/p2p/12D3KooWCW3LGUtkCVkHZmVSZHzL3C4WRKWfqAiJPz1NR7dT9Bxh,/dns4/t-guardian-02.nodes.stable.io/udp/8999/quic/p2p/12D3KooWJXA6goBCiWM8ucjzc4jVUBSqL9Rri6UpjHbkMPErz5zK"
    ports:
      - "7073:7073"
    platform: linux/amd64
      
  orbital_relayer:
    depends_on:
      - guardiand
      - redis
    image: devarogundade/orbital_relayer:latest
    container_name: orbital_relayer
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - SPY_HOST=guardiand:7073

volumes:
  redis-data: